# HipAAsynth — Synthetic health data fairness testing for invisible populations.
# Copyright (C) 2026 HipAAsynth Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
Configuration module for Synthetic Clinical Cohort Engine.

This module defines version constants, default weights, and the GenerationConfig
dataclass used to control synthetic patient generation parameters.
"""

from dataclasses import dataclass
from typing import Optional

# Version constants — single source of truth for the entire codebase.
# All modules import from here; never define ENGINE_VERSION locally.
# Rule: bump ENGINE_VERSION → update CHANGELOG to match. That's it.
ENGINE_VERSION      = "1.0.5"
SCHEMA_VERSION      = "1.0.5"
ADVERSARIAL_VERSION = "1.0.5"

# Default ethnicity weights (sum to 1.0)
DEFAULT_ETHNICITY_WEIGHTS = {
    "white": 0.60,
    "black": 0.12,
    "hispanic": 0.18,
    "asian": 0.06,
    "native": 0.02,
    "other": 0.02,
}

# Allowed conditions in v1
ALLOWED_CONDITIONS = [
    "type2_diabetes",
    "hypertension",
    "hyperlipidemia",
    "chronic_kidney_disease",
    "copd",
    "depression",
    "asthma",
    "congestive_heart_failure",
    "atrial_fibrillation",
    "coronary_artery_disease",
]

# Default synthetic data disclaimer
DEFAULT_SYNTHETIC_DISCLAIMER = (
    "This record contains fully synthetic data generated by a computer algorithm. "
    "No real patient information is present. This data is intended for research, "
    "testing, and development purposes only."
)


@dataclass(frozen=True)
class GenerationConfig:
    """
    Configuration object for controlling synthetic patient generation.

    Attributes:
        patient_count: Number of patient records to generate
        seed: Optional global seed for reproducibility. If None, uses random seed.
        age_min: Minimum age for all patients (inclusive)
        age_max: Maximum age for all patients (inclusive)
        required_condition: Optional condition that must be present in every record
        sex_ratio_female: Probability of female sex (0.0 to 1.0)
        ethnicity_weights: Optional dict mapping ethnicity to weight. If None, uses defaults.
        include_visits: Whether to generate visit records
        include_labs: Whether to generate lab results
        visits_min: Minimum number of visits per patient (if include_visits=True)
        visits_max: Maximum number of visits per patient (if include_visits=True)
        synthetic_disclaimer: Disclaimer text to include in all records
        run_date: Run date in YYYY-MM-DD format
        age_band_weights: Optional list of (min_age, max_age, weight) tuples
        population_profile_path: Optional path to a population profile JSON file
        profile_name: Optional name of the applied population profile
    """
    patient_count: int
    seed: Optional[int]
    age_min: int
    age_max: int
    required_condition: Optional[str]
    sex_ratio_female: float
    ethnicity_weights: Optional[dict[str, float]]
    include_visits: bool
    include_labs: bool
    visits_min: int
    visits_max: int
    synthetic_disclaimer: str
    run_date: str  # "YYYY-MM-DD"
    age_band_weights: Optional[list[tuple[int, int, float]]] = None
    population_profile_path: Optional[str] = None
    profile_name: Optional[str] = None

    def __post_init__(self):
        """Validate configuration parameters."""
        if self.patient_count < 1:
            raise ValueError("patient_count must be at least 1")
        if self.age_min < 0:
            raise ValueError("age_min must be non-negative")
        if self.age_max < self.age_min:
            raise ValueError("age_max must be >= age_min")
        if not 0.0 <= self.sex_ratio_female <= 1.0:
            raise ValueError("sex_ratio_female must be between 0.0 and 1.0")

        if self.ethnicity_weights is not None:
            total = sum(self.ethnicity_weights.values())
            if not 0.99 <= total <= 1.01:
                raise ValueError(f"ethnicity_weights must sum to 1.0, got {total}")

        if self.age_band_weights is not None:
            if len(self.age_band_weights) == 0:
                raise ValueError("age_band_weights cannot be empty")
            total = sum(weight for _, _, weight in self.age_band_weights)
            if not 0.99 <= total <= 1.01:
                raise ValueError(f"age_band_weights must sum to 1.0, got {total}")
            for lo, hi, weight in self.age_band_weights:
                if lo < 0 or hi < lo:
                    raise ValueError(f"Invalid age band: {(lo, hi, weight)}")
                if weight < 0.0:
                    raise ValueError(f"Age band weight must be non-negative: {(lo, hi, weight)}")

        if self.include_visits:
            if self.visits_min < 0:
                raise ValueError("visits_min must be non-negative")
            if self.visits_max < self.visits_min:
                raise ValueError("visits_max must be >= visits_min")