# HipAAsynth — Synthetic health data fairness testing for invisible populations.
# Copyright (C) 2026 HipAAsynth Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
Configuration module for Synthetic Clinical Cohort Engine.

This module defines version constants, default weights, and the GenerationConfig
dataclass used to control synthetic patient generation parameters.
"""

from dataclasses import dataclass, field
from datetime import date
from typing import Optional

# Version constants — single source of truth for the entire codebase.
ENGINE_VERSION      = "1.0.0"
SCHEMA_VERSION      = "1.0.0"
ADVERSARIAL_VERSION = "1.0.0"

# Default ethnicity weights (sum to 1.0)
DEFAULT_ETHNICITY_WEIGHTS = {
    "white": 0.60,
    "black": 0.12,
    "hispanic": 0.18,
    "asian": 0.06,
    "native": 0.02,
    "other": 0.02,
}

# Allowed conditions in v1
ALLOWED_CONDITIONS = [
    "type2_diabetes",
    "hypertension",
    "hyperlipidemia",
    "chronic_kidney_disease",
    "copd",
    "depression",
    "asthma",
    "congestive_heart_failure",
    "atrial_fibrillation",
    "coronary_artery_disease",
]

# Default synthetic data disclaimer
DEFAULT_SYNTHETIC_DISCLAIMER = (
    "This record contains fully synthetic data generated by a computer algorithm. "
    "No real patient information is present. This data is intended for research, "
    "testing, and development purposes only."
)


@dataclass(frozen=True)
class GenerationConfig:
    """
    Configuration object for controlling synthetic patient generation.

    All parameters have sensible defaults so the engine runs with minimal
    configuration. Override only what you need.

    Attributes:
        patient_count: Number of patient records to generate.
        seed: Seed for reproducibility. Same seed always produces the same output.
        age_min: Minimum patient age (inclusive).
        age_max: Maximum patient age (inclusive).
        required_condition: If set, every patient will have this condition.
        sex_ratio_female: Probability of female sex (0.0–1.0).
        ethnicity_weights: Dict mapping ethnicity to weight. Uses defaults if None.
        include_visits: Whether to generate visit records.
        include_labs: Whether to generate lab results within visits.
        visits_min: Minimum visits per patient (when include_visits=True).
        visits_max: Maximum visits per patient (when include_visits=True).
        synthetic_disclaimer: Disclaimer text embedded in every record.
        run_date: Run date in YYYY-MM-DD format. Defaults to today.
        age_band_weights: Optional list of (min_age, max_age, weight) tuples.
        population_profile_path: Optional path to a population profile JSON file.
        profile_name: Optional name of the applied population profile.
    """
    patient_count: int = 10
    seed: Optional[int] = 42
    age_min: int = 18
    age_max: int = 90
    required_condition: Optional[str] = None
    sex_ratio_female: float = 0.5
    ethnicity_weights: Optional[dict] = None
    include_visits: bool = True
    include_labs: bool = True
    visits_min: int = 1
    visits_max: int = 3
    synthetic_disclaimer: str = DEFAULT_SYNTHETIC_DISCLAIMER
    run_date: str = field(default_factory=lambda: date.today().isoformat())
    age_band_weights: Optional[list] = None
    population_profile_path: Optional[str] = None
    profile_name: Optional[str] = None

    def __post_init__(self):
        """Validate configuration parameters."""
        if self.patient_count < 1:
            raise ValueError("patient_count must be at least 1")
        if self.age_min < 0:
            raise ValueError("age_min must be non-negative")
        if self.age_max < self.age_min:
            raise ValueError("age_max must be >= age_min")
        if not 0.0 <= self.sex_ratio_female <= 1.0:
            raise ValueError("sex_ratio_female must be between 0.0 and 1.0")

        if self.ethnicity_weights is not None:
            total = sum(self.ethnicity_weights.values())
            if not 0.99 <= total <= 1.01:
                raise ValueError(f"ethnicity_weights must sum to 1.0, got {total}")

        if self.age_band_weights is not None:
            if len(self.age_band_weights) == 0:
                raise ValueError("age_band_weights cannot be empty")
            total = sum(weight for _, _, weight in self.age_band_weights)
            if not 0.99 <= total <= 1.01:
                raise ValueError(f"age_band_weights must sum to 1.0, got {total}")
            for lo, hi, weight in self.age_band_weights:
                if lo < 0 or hi < lo:
                    raise ValueError(f"Invalid age band: {(lo, hi, weight)}")
                if weight < 0.0:
                    raise ValueError(f"Age band weight must be non-negative: {(lo, hi, weight)}")

        if self.include_visits:
            if self.visits_min < 0:
                raise ValueError("visits_min must be non-negative")
            if self.visits_max < self.visits_min:
                raise ValueError("visits_max must be >= visits_min")
